"""First Migration

Revision ID: fd5682335ea4
Revises: 
Create Date: 2026-04-17 08:28:27.306853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5682335ea4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transaction',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.Enum('CREDIT', 'DEBIT', name='transactiontype'), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.Column('reciever_account_id', sa.String(), nullable=False),
    sa.Column('sender_account_id', sa.String(), nullable=False),
    sa.Column('transaction_status', sa.Enum('COMPLETED', 'IN_PROCESS', 'FAILED', name='transactionstatus'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_contact_no', sa.String(), nullable=False),
    sa.Column('user_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('Account',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('Bank_name', sa.Enum('SBI', 'HDFC', 'KOTAK', 'ICICI', name='banks'), nullable=False),
    sa.Column('Account_number', sa.String(), nullable=False),
    sa.Column('Account_balance', sa.Integer(), nullable=True),
    sa.Column('Account_type', sa.Enum('SAVINGS', 'CURRENT', 'SALARY', name='accounttype'), nullable=True),
    sa.Column('IFSC_Code', sa.Integer(), nullable=False),
    sa.Column('Pan_Card', sa.String(), nullable=False),
    sa.Column('Adhaar_Card', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('Account_number')
    )
    op.create_index(op.f('ix_Account_Account_number'), 'Account', ['Account_number'], unique=False)
    op.create_table('Wallet',
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('wallet_balance', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Wallet')
    op.drop_index(op.f('ix_Account_Account_number'), table_name='Account')
    op.drop_table('Account')
    op.drop_table('User')
    op.drop_table('Transaction')
    # ### end Alembic commands ###
